### ISSUE TITLE
Integrity Check Fail when Running Yarn

### ISSUE THREAD

**Issue by digitaldina** [cosmicjs/react-native-twitter-clone#1]
I'll start by saying thanks for the great example! While running the installation steps, I got :
error https://github.com/callstack-io/react-native-fbads/tarball/v4.1.0: Integrity check failed for "react-native-fbads" (computed integrity doesn't match our records, got [censored])

The link doesn't work. I've tried updating npm and yarn, and ran it with sudo. I can't find much help anywhere else. New to this, so I appreciate any guidance!

**Comment by digitaldina** [comment]
woops, sorry! Deleting the `package.json` and `package-lock.json` file then re-adding the package.json file after running yarn solved this. Almost wasted a whole day! Hope this helps someone :) I also had issues with running yarn start since there is no appserver.js file in this repository. I created one and am trying this now

**Comment by dharmendrashah** [comment]
it may be helps me but try first
